# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value


services:
    # Интегратор HWIOAuthBundle в FOSUserBundle
    my_user_provider:
        class: UserBundle\Security\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ['@fos_user.user_manager',  {facebook: facebook_id},  '@user.randomizer']

    # Генератор случайных данных для пользователя
    user.randomizer:
        class: UserBundle\Service\Randomizer

    # Перехват регистрации в FOSUserBundle
    user.listener.registration:
        class: UserBundle\EventListener\RegistrationListener
        arguments: ['@fos_user.user_manager', '@user.randomizer']
        tags:
            - { name: kernel.event_subscriber }
